#!/bin/bash
echo a{a..z} b{a..z} c{a..z} d{a..z} e{a..z} f{a..z} g{a..z} h{a..z} i{a..z} j{a..z} k{a..z} l{a..z} m{a..z} n{a..z} o{a..n} o{p..z} p{a..b} q{a..b} r{a..b} s{a..b} t{a..b} u{a..b} v{a..b} w{a..b} x{a..b} y{a..z} z{a..b} | head -64
